# Generated by Django 4.1.7 on 2023-04-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_cv'),
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumni', models.ManyToManyField(to='alumni.alumni')),
                ('student', models.ManyToManyField(to='student.student')),
            ],
        ),
    ]
