# Generated by Django 4.1.7 on 2023-04-03 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_cv'),
        ('alumni', '0002_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='alumni',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='student',
        ),
        migrations.AddField(
            model_name='feedback',
            name='alumni',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='alumni.alumni'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]
