# Generated by Django 4.1.7 on 2023-04-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_remove_feedback_alumni_remove_feedback_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='text',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
