# Generated by Django 4.1.7 on 2023-04-07 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_cv'),
        ('alumni', '0004_feedback_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback',
            new_name='Chat',
        ),
    ]
