# Generated by Django 4.1.7 on 2023-04-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0005_rename_feedback_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='text',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
    ]
