# Generated by Django 4.1.7 on 2023-04-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_cv'),
        ('alumni', '0006_alter_chat_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='alumni',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='student',
        ),
        migrations.AddField(
            model_name='chat',
            name='alumni',
            field=models.ManyToManyField(to='alumni.alumni'),
        ),
        migrations.AddField(
            model_name='chat',
            name='student',
            field=models.ManyToManyField(to='student.student'),
        ),
    ]
