# Generated by Django 4.1.7 on 2023-04-07 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_cv'),
        ('alumni', '0007_remove_chat_alumni_remove_chat_student_chat_alumni_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='alumni',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='student',
        ),
        migrations.AddField(
            model_name='chat',
            name='alumni',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='alumni.alumni'),
        ),
        migrations.AddField(
            model_name='chat',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]
