# Generated by Django 4.1.7 on 2023-04-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0008_remove_chat_alumni_remove_chat_student_chat_alumni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='isactive',
            field=models.BooleanField(default=False),
        ),
    ]
