# Generated by Django 4.1.7 on 2023-04-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0010_alumni_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='text',
            field=models.CharField(blank=True, default='', max_length=1000000),
        ),
    ]
