# Generated by Django 4.1.7 on 2023-04-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadmin',
            name='c_profile',
            field=models.CharField(choices=[('s', 'SOFTWARE'), ('d', 'DATA'), ('f', 'FINANCE'), ('q', 'QUANT')], default='s', max_length=4),
        ),
    ]
