# Generated by Django 4.1.7 on 2023-04-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_cv'),
        ('cadmin', '0002_alter_cadmin_c_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadmin',
            name='students',
            field=models.ManyToManyField(to='student.student'),
        ),
    ]
