# Generated by Django 4.1.7 on 2023-04-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadmin', '0003_cadmin_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadmin',
            name='ishiring',
            field=models.BooleanField(default=False),
        ),
    ]
