# Generated by Django 4.1.7 on 2023-04-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadmin', '0005_cadmin_isverified'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadmin',
            name='cert',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
