# Generated by Django 4.1.7 on 2023-04-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadmin', '0006_cadmin_cert'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadmin',
            name='about',
            field=models.TextField(blank=True),
        ),
    ]
