# Generated by Django 4.1.7 on 2023-04-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadmin', '0007_cadmin_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadmin',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
