# Generated by Django 4.1.7 on 2023-04-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_remove_student_cv_student_cv_d_student_cv_f_and_more'),
        ('cadmin', '0008_cadmin_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadmin',
            name='students',
            field=models.ManyToManyField(blank=True, to='student.student'),
        ),
    ]
