# Generated by Django 4.1.7 on 2023-04-08 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=10000000)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=100)),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date of Joining')),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('cv_s', models.FileField(blank=True, null=True, upload_to='files/')),
                ('cv_d', models.FileField(blank=True, null=True, upload_to='files/')),
                ('cv_f', models.FileField(blank=True, null=True, upload_to='files/')),
                ('cv_q', models.FileField(blank=True, null=True, upload_to='files/')),
                ('photo', models.FileField(blank=True, null=True, upload_to='files/')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
