# Generated by Django 4.1.7 on 2023-04-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cv',
        ),
        migrations.AddField(
            model_name='student',
            name='cv_d',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='student',
            name='cv_f',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='student',
            name='cv_q',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='student',
            name='cv_s',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
